{% set name = "bmi-geotiff" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc287fd5d884d6ded4ffa33222e7d6971a086d1cc57edd477f8cf74ab9da771c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - rioxarray
    - rasterio
    - pyyaml
    - bmipy

test:
  imports:
    - bmi_geotiff
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/csdms/bmi-geotiff
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    Access data (and metadata) from a GeoTIFF file through an API or a BMI
  description: |
    bmi-geotiff is a Python library that allows a user Basic Model Interface
    (BMI) access to data and metadata in GeoTIFF files through *rioxarray* and
    *rasterio*.
  doc_url: https://bmi-geotiff.readthedocs.io/
  dev_url: https://github.com/csdms/bmi-geotiff

extra:
  recipe-maintainers:
    - mdpiper
