{% set name = "bmi-geotiff" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2e2012ddbe3244bde370114c9fce7ad116e53310315f216d494f070adddf6d41

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - rioxarray
    - rasterio
    - pyyaml
    - bmipy

test:
  imports:
    - bmi_geotiff
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/csdms/bmi-geotiff
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    Access data (and metadata) from a GeoTIFF file through an API or a BMI
  description: |
    bmi-geotiff is a Python library that allows a user Basic Model Interface
    (BMI) access to data and metadata in GeoTIFF files through *rioxarray* and
    *rasterio*.
  doc_url: https://bmi-geotiff.readthedocs.io/
  dev_url: https://github.com/csdms/bmi-geotiff

extra:
  recipe-maintainers:
    - mdpiper
